version: '3'

services:
  app:
    image: 'ms-gestao-pedidos:dev'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-gestao-pedidos
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ms-gestao-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - shared_network
  db:
    image: postgres
    container_name: gestao-pedidos-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-gestao-pedidos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
